services:
  postgres:
    image: postgres:latest
    container_name: fastify-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: fastify-auth
    ports:
      - "5432:5432"
    volumes:
      - fastify_pg_data:/var/lib/postgresql/data

volumes:
  fastify_pg_data:
    driver: local
