version: '3.8'

services:
  db:
    image: postgres:13
    container_name: my-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    restart: always

volumes:
  postgres_data:

networks:
  mynetwork:
    driver: bridge
